college_predictor/college_predictor/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/', include("main.urls")),
]

college_predictor/main/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = "main"

urlpatterns = [
    path("", views.index, name="index"),
    path("home/", views.home, name="home"),
    path("about-us/", views.aboutUs, name="aboutUs"),
    path("contact-us/", views.contactUs, name="contactUs"),
    path("login/", views.loginview, name="login"),
    path("logout/", views.logoutview, name="logout"),
    path("search/", views.searchresult, name="searchresult"),
    path("mail/", views.mail, name="mail"),
    path("signup/", views.signup, name="signup"),
    path("search/q1/", views.query1, name="query1"),
    path("search/q2/", views.query2, name="query2"),
    path("search/q3/", views.query3, name="query3"),
]

college_predictor/main/models.py
from django.db import models

# Create your models here.

class college_details(models.Model):
    Eamcet_Code=models.CharField(max_length=6,primary_key=True,blank=True)
    College_Name=models.CharField(max_length=100,blank=True)
    District=models.CharField(max_length=20,blank=True)
    Place=models.CharField(max_length=30,blank=True)
    Contact_No=models.CharField(max_length=10,null=True)
    Website=models.URLField(null=True)
    College_Type=models.CharField(max_length=5,null=True,blank=True)
    Coed=models.CharField(max_length=5,null=True,blank=True)
    Size=models.CharField(max_length=5,null=True,blank=True)
    Academics_Quality=models.CharField(max_length=5,null=True,blank=True)
    Placement_Rating=models.CharField(max_length=5,null=True,blank=True)
    Sports=models.CharField(max_length=5,null=True,blank=True)
    Hostel_B=models.CharField(max_length=5,null=True,blank=True)
    Hostel_G=models.CharField(max_length=5,null=True,blank=True)
    Bus_Facility=models.CharField(max_length=5,null=True,blank=True)
    Clubs=models.CharField(max_length=5,null=True,blank=True)
    Medical_Care=models.CharField(max_length=5,null=True,blank=True)
    NIRF=models.CharField(max_length=5,null=True,blank=True)
    NAAC=models.CharField(max_length=4,null=True)
    NBA=models.CharField(max_length=5,null=True,blank=True)


class cutoff(models.Model):
    Eamcet_Code=models.CharField(max_length=6,null=True)
    Course_Code=models.CharField(max_length=3,blank=True)
    Region=models.CharField(max_length=3,blank=True)
    District=models.CharField(max_length=20,blank=True)
    Place=models.CharField(max_length=30,blank=True)
    ocb=models.CharField(max_length=10,null=True,blank=True)
    ocg=models.CharField(max_length=10,null=True,blank=True)
    scb=models.CharField(max_length=10,null=True,blank=True)
    scg=models.CharField(max_length=10,null=True,blank=True)
    stb=models.CharField(max_length=10,null=True,blank=True)
    stg=models.CharField(max_length=10,null=True,blank=True)
    bcab=models.CharField(max_length=10,null=True,blank=True)
    bcag=models.CharField(max_length=10,null=True,blank=True)
    bcbb=models.CharField(max_length=10,null=True,blank=True)
    bcbg=models.CharField(max_length=10,null=True,blank=True)
    bccb=models.CharField(max_length=10,null=True,blank=True)
    bccg=models.CharField(max_length=10,null=True,blank=True)
    bcdb=models.CharField(max_length=10,null=True,blank=True)
    bcdg=models.CharField(max_length=10,null=True,blank=True)
    bcdb=models.CharField(max_length=10,null=True,blank=True)
    bcdg=models.CharField(max_length=10,null=True,blank=True)
    bceb=models.CharField(max_length=10,null=True,blank=True)
    bceg=models.CharField(max_length=10,null=True,blank=True)

college_predictor/main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Firstname'
    }) ,max_length=30, help_text='Required.')
    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Lastname'
    }) ,max_length=30, help_text='Required.')
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        'placeholder':'Email'
    }) ,max_length=254, help_text='Required. Inform a valid email address.')


    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )
        widgets = {
            'username': forms.TextInput(attrs={'placeholder': 'Username'}),
            'password1': forms.PasswordInput(attrs={'placeholder': 'Enter Password'}),
            'password2': forms.PasswordInput(attrs={'placeholder': 'COnfirm Password'}),
        }

college_predictor/main/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.core.mail import send_mail
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.template.loader import render_to_string
from django.utils.html import strip_tags
from .models import college_details, cutoff
import pandas as pd
import numpy as np
import math as m
from main.forms import SignUpForm


# Create your views here.

def index(request):
    if request.user.is_authenticated:
         return render(request, "main/index.html", {
             'check': True,
         })
    return render(request,"main/index.html", {
        'check': False,
    })


def home(request):
    if request.user.is_authenticated:
        return render(request, "main/home.html", {
             'check': True,
         })
    return render(request,"main/home.html", {
        'check': False,
    })


def searchresult(request):
    if request.method == 'GET':
        searchname=request.GET['search-box']
        q01=cutoff.objects.all().values('Eamcet_Code','Course_Code')
        q01=pd.DataFrame(list(q01))
        q02=pd.DataFrame(list(college_details.objects.all().values('Eamcet_Code','College_Name','District','Place','Contact_No','Website','NBA','NAAC','NIRF').filter(College_Name__icontains=searchname)))
        if q02.empty:
            return render(request, "main/search.html", {
            'check': request.user.is_authenticated,
            'qs':list(pd.DataFrame()),
            'errors':True,
        })
        q0=pd.merge(q01,q02,how="inner",left_on="Eamcet_Code",right_on="Eamcet_Code")
        q0=q0.applymap(lambda x: None if x == '' else x)
        return render(request, "main/search.html", {
            'check': request.user.is_authenticated,
            'qs':list(q0.T.to_dict().values()),
            'errors':False,
        })
    return render(request, "main/search.html", {
            'check': request.user.is_authenticated,
            'qs':list(pd.DataFrame()),
            'errors':True,
        })


def mail(request):
    if 'curr_user' in request.session and request.user.username == request.session['curr_user']:
        html_message = render_to_string('main/email.html', {
            'user':request.session['curr_user'],
            'qs':request.session['result'],
            'preferences':request.session['preferences'],
            'querytype':request.session['querytype']
            })
        plain_message = strip_tags(html_message)
        send_mail(
                "Your College List From College Predictor",
                plain_message,
                '18135a0520@gvpce.ac.in',
                [request.user.email],
                html_message=html_message
            )
        return render(request,"main/success.html")
    return HttpResponseRedirect(reverse("main:login"))


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            request.session['curr_user']=username
            login(request, user)
            return HttpResponseRedirect(reverse('main:home'))
        # else:
        #     form = SignUpForm()
        #     return render(request, 'main/login.html', {'form': form})
    else:
        form = SignUpForm()
    return render(request, 'main/login.html', {'form': form})


def loginview(request):
    if request.user.is_authenticated:
         return render(request, "main/login.html", {
             'check': True,
         })
    
    if request.method=="POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user is not None:
            request.session['curr_user']=username
            login(request, user)
            return HttpResponseRedirect(reverse("main:home"))
        else:
            form=SignUpForm()
            return render(request, "main/login.html", {
                "message": "Invalid Credentials",
                'form':form,
            })
    else:
        form=SignUpForm()
    return render(request,"main/login.html",{
        'check':False,
        'form': form
    })


def logoutview(request):
    logout(request)
    return render(request, "main/logout.html")


def aboutUs(request):
    if request.user.is_authenticated:
         return render(request, "main/about.html", {
             'check': True,
         })
    return render(request,"main/about.html", {
        'check': False,
    })


def contactUs(request):
    if request.user.is_authenticated:
         return render(request, "main/contact.html", {
             'check': True,
         })
    return render(request,"main/contact.html", {
        'check': False,
    })


def query1(request):
    if request.method == 'GET':
        district=request.GET['choice-district']
        q11=cutoff.objects.filter(District__exact=district).all().values('Eamcet_Code','Course_Code')
        q11=pd.DataFrame(list(q11))
        q12=pd.DataFrame(list(college_details.objects.filter(District__exact=district).all().values()))
        if 'Gender' in request.GET:
            gender=request.GET['Gender']
        else:
            gender='B'
        q12, preferences_list,academics,placements,coll_size,coll_type=clean_data(request,df= q12, gender=gender)
        preferences=False
        q12['percentage']=0
        if 'preferences-checkbox' in request.GET and request.GET['preferences-checkbox']=="on":
            preferences=True
            q12['percentage'] = q12.apply(lambda row:calculate_percentage(row,preferences_list=preferences_list,academics=academics,placements=placements,coll_size=coll_size,coll_type=coll_type),axis=1) 
        q1=pd.merge(q11,q12,how="inner",left_on="Eamcet_Code",right_on="Eamcet_Code")
        q1=q1[['Eamcet_Code','College_Name','Course_Code','District','Place','Contact_No','Website','NBA','NAAC','NIRF','percentage']]
        if not 'result' in request.session:
            request.session['result']=list(q1.T.to_dict().values())
        else:
            request.session['result']=list(q1.T.to_dict().values())

        if not 'preferences' in request.session:
            request.session['preferences']=preferences
        else:
            request.session['preferences']=preferences

        if not 'querytype' in request.session:
            request.session['querytype']=1
        else:
            request.session['querytype']=1
        return render(request, "main/result.html", {
            'check': request.user.is_authenticated,
            'qs':list(q1.T.to_dict().values()),
            'preferences':preferences,
            'querytype':1,
        })
    return render(request,"main/home.html", {
        'check': request.user.is_authenticated,
    })


def query2(request):
    if request.method == 'GET':
        rank=int(request.GET["rank"])
        category=request.GET["choice-caste"]
        if request.GET["gender-out"] == 'Male':
            category+='b'
            gender='B'
        elif request.GET["gender-out"] == 'Female':
            category+='g'
            gender='G'
        q21=cutoff.objects.all().values('Eamcet_Code','Course_Code',category)
        q21=pd.DataFrame(list(q21))
        q21=q21[q21[category]!='']
        q21[category]=(q21[category]).astype(int)
        q21=q21[q21[category]>=rank]
        q22=pd.DataFrame(list(college_details.objects.all().values()))
        q22, preferences_list,academics,placements,coll_size,coll_type=clean_data(request,df= q22, gender=gender)
        preferences=False
        q22['percentage']=0
        if 'preferences-checkbox' in request.GET and request.GET['preferences-checkbox']=="on":
            preferences=True
            q22['percentage'] = q22.apply(lambda row:calculate_percentage(row,preferences_list=preferences_list,academics=academics,placements=placements,coll_size=coll_size,coll_type=coll_type),axis=1) 
        q2=pd.merge(q21,q22,how="inner",left_on="Eamcet_Code",right_on="Eamcet_Code")
        q2=q2[['Eamcet_Code','College_Name','Course_Code','District','Place','Contact_No','Website','NBA','NAAC','NIRF','percentage']]
        if not 'result' in request.session:
            request.session['result']=list(q2.T.to_dict().values())
        else:
            request.session['result']=list(q2.T.to_dict().values())

        if not 'preferences' in request.session:
            request.session['preferences']=preferences
        else:
            request.session['preferences']=preferences

        if not 'querytype' in request.session:
            request.session['querytype']=2
        else:
            request.session['querytype']=2
        return render(request, "main/result.html", {
            'check': True,
            'qs':list(q2.T.to_dict().values()),
            'preferences':preferences,
            'querytype':2,
    })
    return render(request,"main/home.html", {
        'check': request.user.is_authenticated,
    })
    

def query3(request):
    if request.method == 'GET':
        district=request.GET["choice-district"]
        rank=int(request.GET["rank"])
        category=request.GET["choice-caste"]
        if request.GET["gender-out"] == 'Male':
            category+='b'
            gender='B'
        elif request.GET["gender-out"] == 'Female':
            category+='g'
            gender='G'
        q31=cutoff.objects.all().filter(District__exact=district).values('Eamcet_Code','Course_Code',category)
        q31=pd.DataFrame(list(q31))
        q31=q31[q31[category]!='']
        q31[category]=(q31[category]).astype(int)
        q31=q31[q31[category]>=rank]
        q32=pd.DataFrame(list(college_details.objects.filter(District__exact=district).all().values()))

college_predictor/main/templates/main/about.html
{% extends 'main/layout.html' %}
{% load static %}

{% block head %}
<title>CollegePredictor</title>
<link rel="stylesheet" href="{% static 'main/styles.css' %}">
<link rel="stylesheet" href="{% static 'main/a.css' %}">
{% endblock %}

{% block body %}
<div class="topnav">
    <label>College Predictor</label>
    <div class="search-container">
        <form action="{% url 'main:searchresult' %}" method="GET">
            <input name="search-box" type="text" placeholder="Type College Name">
            <button type="submit" value="Enter" style="color: grey;">Enter</button>
        </form>
    </div>
    {% if check %}
    <a href="{% url 'main:logout' %}">Logout</a>
    <a href="{% url 'main:contactUs' %}">Contact Us</a>
    <a href="{% url 'main:aboutUs' %}" class="active">About Us</a>
    <a href="{% url 'main:home' %}">Home</a>
    {% else %}
    <a href="{% url 'main:contactUs' %}">Contact Us</a>
    <a href="{% url 'main:aboutUs' %}" class="active">About Us</a>
    <a href="{% url 'main:login' %}">Login/Signup</a>
    <a href="{% url 'main:home' %}">Home</a>
    {% endif %}
</div>


<div class="context">
    <h4><strong>OVERVIEW OF OUR PROJECT : </strong></h4>
    <ul>
        <li>As soon as a student completes his/her intermediate education, the first goal of any student is to get into
            an appropriate Undergraduate College.
            Students face difficulty inorder to choose a right college. So, our COLLEGE PREDICTOR project helps them in
            choosing a better college for him/her based on their preferences.</li>
        <br>
        <li>College Predictor is a web-based application, where student inputs his/her competitive rank like that of
            Eamcet, Caste and Gender.
            These three are the key attributes for any placement in any college under any Board Of Education, especially
            in India.
            Our College Predictor only works for Engineering Category.Along with the key fields, user may choose to give
            their own preferences in various facilities and services offered by the colleges
            like College Type, Bus Facility, Hostel, Sports, Medical Care, etc.Based on these preferences taken from the
            student, we shall provide you a match percentile for every college that qualifies
            you based on your rank. College Predictor displays the list of colleges on a webpage as a response. So, all
            you need to do is to fill a small form in the Homepage and click on submit.
            In a few seconds your result shall be displayed.
            The result(list of colleges) include columns such as Eamcet Code, College Name, Course Code, Place, Contact
            No, Website, NBA Accreditation, NAAC Rating, NIRF Ranking, Preferences Match %.</li>
        <br>
        <li>We have also provided an automated e-mail generator mechanism especially for the authorised users only,
            which sends the last result queried by the user.
            So, you need to make sure you need to signed up and logged into your account.</li>
    </ul>
    <h4><strong>STEPS TO VIEW YOUR RESULT : </strong></h4>
    <ol>
        <li>Go to Login/SignUp page and register using signup form.</li>
        <li>If you are already an existing user, don't forget to login using the Login/SignUp page.</li>
        <li>Go to Homepage choose the type of form and fill it with all your preferences and the necessary fields, and
            submit it.</li>
        <li>After a few seconds, you will be redirected to your result</li>
        <li>You don't need to note down your result, feel free to use the mail service provided by us.</li>
    </ol>
</div>

{% endblock %}

college_predictor/main/templates/main/contact.html
{% extends 'main/layout.html' %}
{% load static %}

{% block head %}
<title>CollegePredictor</title>
<link rel="stylesheet" href="{% static 'main/ct.css' %}">
<link rel="stylesheet" href="{% static 'main/styles.css' %}">
{% endblock %}

{% block body %}
    <div class="topnav">
        <label>College Predictor</label>
        <div class="search-container">
            <form action="{% url 'main:searchresult' %}" method="GET">
                <input name="search-box" type="text" placeholder="Type College Name">
                <button type="submit" value="Enter" style="color: grey;">Enter</button>
            </form>  
        </div>
        {% if check %}
        <a href="{% url 'main:logout' %}" >Logout</a>
        <a href="{% url 'main:contactUs' %}" class="active">Contact Us</a>
        <a href="{% url 'main:aboutUs' %}">About Us</a>
        <a href="{% url 'main:home' %}" >Home</a>
        {% else %}
        <a href="{% url 'main:contactUs' %}" class="active">Contact Us</a>
        <a href="{% url 'main:aboutUs' %}">About Us</a>
        <a href="{% url 'main:login' %}" >Login/Signup</a>
        <a href="{% url 'main:home' %}" >Home</a>
        {% endif %}
    </div>

    <div class="container">
        <div class="co">
            <h2>Contact Us At</h2>
        </br>
            <p>Phone No: 9652225075, 9247866988, 6303486927, 8919941861<br></p>
            <p>Email: <i>sravani.cme14@gmail.com</i>            </p>
        </div>
    </div>

{% endblock %}

college_predictor/main/templates/main/layout.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="icon" href='https://banner2.cleanpng.com/20171128/e51/owl-with-school-books-png-clipart-picture-5a1d4f068b3477.5771033115118702145702.jpg' type="image/x-icon">
        {% block head %}

        {% endblock %}
    </head>
    
    <body>

        {% block body %}
        {% endblock %}

    </body>
</html>

college_predictor/main/templates/main/login.html
{% extends 'main/layout.html' %}
{% load static %}

{% block head %}
<title>CollegePredictor</title>
<link rel="stylesheet" href="{% static 'main/styles.css' %}">
<link rel="stylesheet" href="{% static 'main/lin.css' %}">
<link rel="stylesheet" href="{% static 'main/dualtab.css' %}">

<script type="text/javascript">

  let flag;

  document.addEventListener('DOMContentLoaded', () => {

    document.getElementById('id_password1').placeholder = "Type Password";
    document.getElementById('id_password2').placeholder = "Confirm Password";

    if (window.location.pathname === "/main/login/") {
      flag = true;
      document.querySelector('.signup').style.display = 'none';
      document.querySelector('.signin').style.display = 'initial';
      document.querySelector('.s1class').style.color = '#f69009';
      document.querySelector('.s2class').style.color = '#748194';
      document.querySelector('#left').classList.add('left_hover');
      document.querySelector('#right').classList.remove('right_hover');
    }
    else {
      flag = false;
      document.querySelector('.signin').style.display = 'none';
      document.querySelector('.signup').style.display = 'initial';
      document.querySelector('.s1class').style.color = '#748194';
      document.querySelector('.s2class').style.color = '#0abd60';
      document.querySelector('#left').classList.remove('left_hover');
      document.querySelector('#right').classList.add('right_hover');
    }

  });

  if (flag) {
    function left() {
      document.querySelector('.signup').style.display = 'none';
      document.querySelector('.signin').style.display = 'initial';
      document.querySelector('.s1class').style.color = '#f69009';
      document.querySelector('.s2class').style.color = '#748194';
      document.querySelector('#left').classList.add('left_hover');
      document.querySelector('#right').classList.remove('right_hover');
    }

    function right() {
      document.querySelector('.signup').style.display = 'initial';
      document.querySelector('.signin').style.display = 'none';
      document.querySelector('.s2class').style.color = '#0abd60';
      document.querySelector('.s1class').style.color = '#748194';
      document.querySelector('#right').classList.add('right_hover');
      document.querySelector('#left').classList.remove('left_hover');
    }
  }
  else {
    function right() {
      document.querySelector('.signin').style.display = 'none';
      document.querySelector('.signup').style.display = 'initial';
      document.querySelector('.s1class').style.color = '#748194';
      document.querySelector('.s2class').style.color = '#0abd60';
      document.querySelector('#left').classList.remove('left_hover');
      document.querySelector('#right').classList.add('right_hover');
    }

    function left() {
      document.querySelector('.signup').style.display = 'none';
      document.querySelector('.signin').style.display = 'initial';
      document.querySelector('.s1class').style.color = '#f69009';
      document.querySelector('.s2class').style.color = '#748194';
      document.querySelector('#left').classList.add('left_hover');
      document.querySelector('#right').classList.remove('right_hover');
    }
  }

  function pass_on() {
    location.href = '/main/';
  }
</script>

{% endblock %}

{% block body %}

{% if not check %}

<div class="topnav">
  <label>College Predictor</label>
  <div class="search-container">
    <form action="{% url 'main:searchresult' %}" method="GET">
      <input name="search-box" type="text" placeholder="Type College Name">
      <button type="submit" value="Enter" style="color: grey;">Enter</button>
    </form>
  </div>

  <a href="{% url 'main:contactUs' %}">Contact Us</a>
  <a href="{% url 'main:aboutUs' %}">About Us</a>
  <a href="{% url 'main:login' %}" class="active">Login/Signup</a>
  <a href="{% url 'main:home' %}">Home</a>

</div>

<div class="context">
  <div class="container">

    <div class="c1">
      <div class="c11">
      </div>
      <div id="left" onclick="left()">
        <h1 class="s1class"><span>LOG</span><span class="su">IN</span>
        </h1>
      </div>
      <div id="right" onclick="right()">
        <h1 class="s2class"><span>SIGN</span><span class="su">UP</span></h1>
      </div>
    </div>

    <div class="c2">
      <form action="{% url 'main:signup' %}" method="POST" class="signup">
        <h1 class="c2-title">SIGN UP</h1>

        {% csrf_token %}


        <div class="tooltip">
          {{ form.username }}
          <span class="tooltiptext">
            {{ form.username.help_text }}
          </span>
        </div>

        {% if form.username.errors %}
        <small style='color:red;margin-left: 10px;'>Username already taken or invalid, Follow tooltip</small>
        {% endif %}

        <div class="tooltip">
          {{ form.first_name }}
          <span class="tooltiptext">
            {{ form.first_name.help_text }}
          </span>
        </div>

        {% if form.first_name.errors %}
        <small style='color:red;margin-left: 10px;'>Please fill this field</small>
        {% endif %}

        <div class="tooltip">
          {{ form.last_name }}
          <span class="tooltiptext">
            {{ form.last_name.help_text }}
          </span>
        </div>

        {% if form.last_name.errors %}
        <small style='color:red;margin-left: 10px;'>Please fill this field</small>
        {% endif %}

        <div class="tooltip">
          {{ form.email }}
          <span class="tooltiptext">
            {{ form.email.help_text }}
          </span>
        </div>

        {% if form.email.errors %}
        <small style='color:red;margin-left: 10px;'>Enter a valid email address</small>
        {% endif %}

        <div class="tooltip">
          {{ form.password1 }}
          <span class="tooltiptext">
            {{ form.password1.help_text }}
          </span>
        </div>

        {% if form.password1.errors %}
        <small style='color:red;margin-left: 10px;'>Please use the help of tooltip text</small>
        {% endif %}

        <div class="tooltip">
          {{ form.password2 }}
          <span class="tooltiptext">
            {{ form.password2.help_text }}
          </span>
        </div>

        {% if form.password2.errors %}
        <small style='color:red;margin-left: 10px;'>Passwords didn't match or too similar to personal info.</small>
        {% endif %}


        <button class="btn">Sign Up</button>
      </form>

      <form action="{% url 'main:login' %}" method="POST" class="signin">
        <h1 class="c2-title">LOG IN</h1>
        {% csrf_token %}
        <div style="text-align: center; padding-top: 20px; color:red">
          {% if message %}
          {{message}}
          {% endif %}
        </div>

        <br><br><br><br>
        <div class="tooltip">
          <input name="username" type="text" placeholder="Username" class="inp" />
          <span class="tooltiptext">Please fill your Username</span>
        </div>
        <div class="tooltip">
          <input name="password" type="password" placeholder="Password" class="inp" />
          <span class="tooltiptext">Please Type Your Password</span>
        </div>
        <button class="btn">Check In</button>

      </form>

    </div>
  </div>
</div>


{% else %}

<div class="topnav">
  <label>College Predictor</label>
  <div class="search-container">
    <form action="">
      <input type="text" placeholder="Search.." name="search">
      <button type="submit" value="Enter" style="color: grey;">Enter</button>
    </form>
  </div>

  <a href="{% url 'main:logout' %}">Logout</a>
  <a href="{% url 'main:contactUs' %}">Contact Us</a>
  <a href="{% url 'main:aboutUs' %}">About Us</a>
  <a href="{% url 'main:home' %}">Home</a>
</div>


<script type="text/javascript">

  pass_on();
</script>
{% endif %}

{% endblock %}

college_predictor/main/templates/main/logout.html
{% extends 'main/layout.html' %}
{% load static %}

{% block head %}
<title>CollegePredictor</title>
<link rel="stylesheet" href="{% static 'main/styles.css' %}">
<link rel="stylesheet" href="{% static 'main/lout.css' %}">

<script>
    document.addEventListener('DOMContentLoaded', () => {

        var seconds = 5;
        var foo;
        function redirect() {
            location.href = "{% url 'main:index' %}";
        }
        function updateSecs() {
            document.querySelector(".context .timer").innerHTML = "You will be redirected to index page in " + seconds + "s.";
            seconds--;
            if (seconds == -1) {
                clearInterval(foo);
                redirect();
            }
        }
        function countdownTimer() {
            foo = setInterval(function () {
                updateSecs()
            }, 1000);
        }
        countdownTimer();
    });

</script>

{% endblock %}

{% block body %}
<div class="topnav">
    <label>College Predictor</label>
    <div class="search-container">
        <form action="{% url 'main:searchresult' %}" method="GET">
            <input name="search-box" type="text" placeholder="Type College Name">
            <button type="submit" value="Enter" style="color: grey;">Enter</button>
        </form>
    </div>
    {% if check %}
    <a href="{% url 'main:logout' %}">Logout</a>
    <a href="{% url 'main:contactUs' %}">Contact Us</a>
    <a href="{% url 'main:aboutUs' %}">About Us</a>
    <a href="{% url 'main:home' %}">Home</a>
    {% else %}
    <a href="{% url 'main:contactUs' %}">Contact Us</a>
    <a href="{% url 'main:aboutUs' %}">About Us</a>
    <a href="{% url 'main:login' %}">Login/Signup</a>
    <a href="{% url 'main:home' %}">Home</a>
    {% endif %}
</div>


<div class="context">
    <p>You are successfully Logged Out.Thank You!</p><br><br>
    <p class="timer"></p>
</div>

{% endblock %}